export { default as Main } from "./Main";
export { default as About } from "./About";
export { default as Project } from "./Project";
export { default as MyNote } from "./MyNote";
export { default as Contact } from "./Contact";
export { default as Login } from "./Login";
export { default as PostCreate } from "./PostCreate";
export { default as PostEdit } from "./PostEdit";
export { default as NotFound } from "./NotFound";
