export { default as Header } from "./Header";
export { default as SubTitle } from "./SubTitle";
export { default as ImgPostList } from "./ImgPostList";
export { default as IntroPostLIst } from "./IntroPostList";
export { default as PostAction } from "./PostAction";
export { default as Dialog } from "./Dialog";
export { default as IntroPost } from "./IntroPost";
export { default as ImgPost } from "./ImgPost";
export { default as MainAnimation } from "./MainAnimation";
